c_compiler:
  - clang  # [unix]
  - vs2022  # [win]
c_compiler_version:  # [unix]
  - 21  # [unix]
cxx_compiler:
  - vs2022  # [win]
  - clangxx  # [unix]
cxx_compiler_version:  # [unix]
  - 21  # [unix]
microarch_level:
  - 1
  - 3  # [unix and x86_64]
